### ISSUE TITLE
UI footer too noisy

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#100]
I think the footer is too noisy

Not sure I need constant access to static info like
board type, serial port, deviot version , pio version 

When I am trying to just see column and line numbers.
Maybe make the footer env string variable or optional

At least consider some tabbing or if sublime allows segments in footer, to make it easer to see line and cols

**Comment by gepd** [comment]
Done, now there is a new option in `Options > Show Information in the Status Bar` and it's only showing the board and serial port selected
