### ISSUE TITLE
device not found for OTA upload

### ISSUE THREAD

**Issue by macmeck** [gepd/Deviot#103]
I have an ESP8266 which is ready for OTA upload. But when I select "Serial Port(s)", all I see is my COM Port and "Add IP Manually". Providing the IP does not help - upload does not start.

Board is ESP01_1M
Deviot v1.2.5
Pio v3.2.1

Seems to be the same on a Win7 and on my Ubuntu system. Am I missing something?

Using the Arduino IDE, OTA works just fine and the device is being detected automatically.

**Comment by pxds** [comment]
I have the same problem as you, "Add IP Manually" does absolutely nothing. The OTA port still shows up and works on Arduino IDE.

Board NodeMCU 1.0
Deviot 1.2.5
PIO 3.2.1
Mac OSX El Captain 10.11.3

**Comment by macmeck** [comment]
Is there anything we can do to track down this issue? It does not seem to be a Wifi issue since the Arduino IDE is working just fine. 
Any config option that needs to be set? Any other idea?

**Comment by pxds** [comment]
I use a WiFi signal extender at home, once i turned it off, NodeMCU started showing much more often as an OTA port, but sometimes it would still fail the upload or disappear from the port list. 

Still clueless on how to solve it.

**Comment by macmeck** [comment]
Well, with current development branch, at least setting the IP address manually seems to be working. Still no automatic discovery of the OTA port though.

**Comment by marcunzueta** [comment]
@macmeck I have the exact same problem. I tested my ESP8266 on Deviot, Sublime Text 3 and I cannot upload by OTA as it is not detected on the serial port, even if I manually introduce the IP; but if I use the Arduino IDE it detects automatically the ESP8266 board and I can upload it without anyproblems

**Comment by gepd** [comment]
Hey guys there is a new version of Deviot with improvements in this subject, it has  not officially release yet, but you can install it following the next instructions: https://github.com/gepd/Deviot/issues/117

I'll thank any feedback

Reopen this topic if you think it's neccesary

**Comment by macmeck** [comment]
took a while for me to test, but seems to be fine now! 👍
