### ISSUE TITLE
deviot doesn't see homebrew's platformio?

### ISSUE THREAD

**Issue by thekelvinliu** [gepd/Deviot#108]
when i try to install deviot via package control, the window showing the install status says that platformio is not found. it then starts to download and install platformio by itself. however, i do have platformio installed via homebrew; it's installed at `/usr/local/bin/platformio`. i can't seem to find any place where i can manually set the path for this. is this expected behavior?

**Comment by gepd** [comment]
I've improved this feature in the in the last version of the plugin, it's not released yet but you can help me to test it, more information here: https://github.com/gepd/Deviot/issues/117

**Comment by gepd** [comment]
Please re open this issue if you need
