### ISSUE TITLE
avrdude: ser_open(): can't open device "unknown": No such file or directory

### ISSUE THREAD

**Issue by schack-lindemann** [gepd/Deviot#110]
Running Sublime Text 3 with Deviot 1.2.5 and PlatformIO 3.3.0 on a Macbook Pro 2016 with macOS 10.12.4

When trying to upload code to Arduino Uno via programmer AVRISP mkII, I get the following error:

"Uploading firmware | avrdude: ser_open(): can't open device "unknown": No such file or directory"

I have selected serialport: /dev/cu.usbmodem1441 and it confirms as the UNO serialport when running serial monitor. Any suggestions as to why or any ideas for a solution.

This is the entire verbose output from deviot console:

[ Deviot 1.2.5 ] 8x8matrix.ino
19:02:32 Uploading firmware | [Tue Apr 18 19:02:32 2017] Processing uno (upload_protocol: stk500v2, platform: atmelavr, board: uno, framework: arduino)
--------------------------------------------------------------------------------
avr-g++ -o "/Users/schack/Documents/Code/src/blink.ino.cpp" -x c++ -fpreprocessed -dD -E "/var/folders/w3/wnrzr7pn1cz86_p__r_dhq_h0000gn/T/tmpxHJutT"
Collected 29 compatible libraries
Looking for dependencies...
Project does not have dependencies
avr-g++ -o .pioenvs/uno/src/blink.ino.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard -Isrc src/blink.ino.cpp
avr-gcc-ar rcs .pioenvs/uno/libFrameworkArduinoVariant.a
avr-gcc-ranlib .pioenvs/uno/libFrameworkArduinoVariant.a
avr-g++ -o .pioenvs/uno/FrameworkArduino/CDC.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/CDC.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial0.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial0.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial1.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial1.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial2.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial2.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial3.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial3.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/IPAddress.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/IPAddress.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/PluggableUSB.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/PluggableUSB.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/Print.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/Print.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/Stream.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/Stream.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/Tone.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/Tone.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/USBCore.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/USBCore.cpp
avr-gcc -o .pioenvs/uno/FrameworkArduino/WInterrupts.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/WInterrupts.c
avr-g++ -o .pioenvs/uno/FrameworkArduino/WMath.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/WMath.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/WString.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/WString.cpp
avr-gcc -x assembler-with-cpp -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard -c -o .pioenvs/uno/FrameworkArduino/_wiring_pulse.o /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/_wiring_pulse.S
avr-g++ -o .pioenvs/uno/FrameworkArduino/abi.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/abi.cpp
avr-gcc -o .pioenvs/uno/FrameworkArduino/hooks.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/hooks.c
avr-g++ -o .pioenvs/uno/FrameworkArduino/main.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/main.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/new.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/new.cpp
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/wiring.c
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring_analog.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_analog.c
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring_digital.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_digital.c
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring_pulse.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_pulse.c
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring_shift.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30300 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10617 -I/Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/schack/.platformio/packages/framework-arduinoavr/variants/standard /Users/schack/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_shift.c
avr-gcc-ar rcs .pioenvs/uno/libFrameworkArduino.a .pioenvs/uno/FrameworkArduino/CDC.o .pioenvs/uno/FrameworkArduino/HardwareSerial.o .pioenvs/uno/FrameworkArduino/HardwareSerial0.o .pioenvs/uno/FrameworkArduino/HardwareSerial1.o .pioenvs/uno/FrameworkArduino/HardwareSerial2.o .pioenvs/uno/FrameworkArduino/HardwareSerial3.o .pioenvs/uno/FrameworkArduino/IPAddress.o .pioenvs/uno/FrameworkArduino/PluggableUSB.o .pioenvs/uno/FrameworkArduino/Print.o .pioenvs/uno/FrameworkArduino/Stream.o .pioenvs/uno/FrameworkArduino/Tone.o .pioenvs/uno/FrameworkArduino/USBCore.o .pioenvs/uno/FrameworkArduino/WInterrupts.o .pioenvs/uno/FrameworkArduino/WMath.o .pioenvs/uno/FrameworkArduino/WString.o .pioenvs/uno/FrameworkArduino/_wiring_pulse.o .pioenvs/uno/FrameworkArduino/abi.o .pioenvs/uno/FrameworkArduino/hooks.o .pioenvs/uno/FrameworkArduino/main.o .pioenvs/uno/FrameworkArduino/new.o .pioenvs/uno/FrameworkArduino/wiring.o .pioenvs/uno/FrameworkArduino/wiring_analog.o .pioenvs/uno/FrameworkArduino/wiring_digital.o .pioenvs/uno/FrameworkArduino/wiring_pulse.o .pioenvs/uno/FrameworkArduino/wiring_shift.o
avr-gcc-ranlib .pioenvs/uno/libFrameworkArduino.a
avr-g++ -o .pioenvs/uno/firmware.elf -Os -mmcu=atmega328p -Wl,--gc-sections -flto -fuse-linker-plugin .pioenvs/uno/src/blink.ino.o -L.pioenvs/uno -Wl,--start-group .pioenvs/uno/libFrameworkArduinoVariant.a .pioenvs/uno/libFrameworkArduino.a -lm -Wl,--end-group
Checking program size
text	   data	    bss	    dec	    hex	filename
948	      0	      9	    957	    3bd	.pioenvs/uno/firmware.elf
avr-objcopy -O ihex -R .eeprom .pioenvs/uno/firmware.elf .pioenvs/uno/firmware.hex
BeforeUpload(["program"], [".pioenvs/uno/firmware.hex"])
avrdude -v -p atmega328p -C /Users/schack/.platformio/packages/tool-avrdude/avrdude.conf -c stk500v2 -U flash:w:.pioenvs/uno/firmware.hex:i

avrdude: Version 6.3, compiled on Jan 17 2017 at 12:01:35
Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
Copyright (c) 2007-2014 Joerg Wunsch

System wide configuration file is "/Users/schack/.platformio/packages/tool-avrdude/avrdude.conf"
User configuration file is "/Users/schack/.avrduderc"
User configuration file does not exist or is not a regular file, skipping

Using Port                    : unknown
Using Programmer              : stk500v2
avrdude: ser_open(): can't open device "unknown": No such file or directory

avrdude done.  Thank you.

*** [program] Error 1
========================== [ERROR] Took 1.44 seconds ==========================

================================== [SUMMARY] ==================================
Environment uno      	[ERROR]
Environment nodemcuv2	[SKIP]
========================== [ERROR] Took 1.44 seconds ==========================
19:02:34 ERROR | it took 1.64s

**Comment by gepd** [comment]
Do you keep haveing this problem?
