### ISSUE TITLE
Error installing package in Sublime text 3

### ISSUE THREAD

**Issue by Kitsune1393** [gepd/Deviot#112]
[ Deviot 1.2.5 ] Instalación
20:54:31 PlatformIO no está instalado
Preparándose para instalarlo. Por favor sea paciente esto podría demorar un poco
20:54:31 Descargando archivos necesarios...
20:54:43 Extrayendo archivos...
20:54:44 Instalando PlatformIO...
20:54:46 Error Creating the virtualenv

**Comment by gepd** [comment]
What OS are using?

Please go to `View > Show Console` and copy all info there an paste here

**Comment by gepd** [comment]
Please re open this issue if you keep haveing this problem
