### ISSUE TITLE
Extra languages submenu with no title

### ISSUE THREAD

**Issue by thinkyhead** [gepd/Deviot#136]
### Operating system

macOS 10.12.5

### Description of problem

Seeing a menu with no title that shows some language options.

![image](https://user-images.githubusercontent.com/698003/28254855-656c6ab8-6a76-11e7-8c5d-e172a200e418.png)

### Steps to Reproduce

New install.

**Comment by gepd** [comment]
Can you please remove `Main.sublime-menu` from `Packages\Deviot\` and restart ST, tell if that solve the problem

did you update the plugin or it was a fresh install? (without any file/folder previously)

**Comment by gepd** [comment]
open this issue again if you keep having problems
