### ISSUE TITLE
Deviot menu still present in Sublime after removing the package

### ISSUE THREAD

**Issue by mtzfactory** [gepd/Deviot#147]
Hi,

I still have the Deviot menu, but empty, in Sublime Text 3 after doing a Package Control: Remove Package... How can completly remove the tool?

My system is a macOS Sierra.

Thanks.

**Comment by gepd** [comment]
Sorry about that, in the package folder, there is another folder called `User` inside of that folder, remove the file `deviot.sublime-settings` and the folder `deviot`.

I will fix this in the next days to remove that files automatically when the plugin is uninstalled

**Comment by gepd** [comment]
Improved this with the commit https://github.com/gepd/Deviot/commit/a0b2ce30982cd508c52c94b1620c7f255248eb3a
