### ISSUE TITLE
DEV extra library asset not found on compile

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#150]
Before report an issue, please make sure it hasn't been reported before.

### Operating system
OSX

### Board used
nodemcu v1
### Description of problem
add extra library folder
include library
compile
ERROR

### Steps to Reproduce
add library to ino
#include library

### Actual Results
/Users/.../projects/microcontrollers/dev/libraries/WiFiManager/examples/AutoConnectWithTimeout/AutoConnectWithTimeout.ino:1:25: fatal error: WiFiManager.h: No such file or directory
#include <WiFiManager.h>

### Expected Results
compile

### Additional info
no debug info available

**Comment by gepd** [comment]
fixed with: https://github.com/gepd/Deviot/commit/0a0484e8a31be8b5087d51ad0b6d7d0008cf45ac

**Comment by gepd** [comment]
Open this issue again if the problem continue
