### ISSUE TITLE
DEV override upload speed not working

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#153]
Before report an issue, please make sure it hasn't been reported before.

### Operating system
osx 
### Board used
nodemcu v1

### Description of problem
override upload speed not working

### Steps to Reproduce
click override upload speed, select 921600

### Actual Results
upload slow

### Expected Results
upload speed to be applied

### Additional info

*You can edit the text above according to your need*

**Comment by tablatronix** [comment]
manually adding to build config works fine

**Comment by gepd** [comment]
Fixed with https://github.com/gepd/Deviot/commit/251c4d9155535ecaab8b0d03081eb7528bc291cd

**Comment by gepd** [comment]
Open this issue again if the problem continue
