### ISSUE TITLE
Installing on Windows with Python 2 and 3

### ISSUE THREAD

**Issue by Suyash458** [gepd/Deviot#159]
Thank you for this package, it's been really helpful!

### Operating System
Windows 10

### Description of problem
I have Python 2 installed, but it's not in the system path because Python 3 is the default interpreter. Is there any way Deviot can detect the Python 2 installation?

**Comment by gepd** [comment]
Where is located your Python2? 
It's usually installed in `C:\Python27` it's your case?

**Comment by Suyash458** [comment]
I've installed Python 2 on a different drive, the path looks like `D:\Software\Python27`

**Comment by gepd** [comment]
Please try this:

Open the file: `pio_install.py` locate in  and replace the line

**Comment by Suyash458** [comment]
It works now, I get a message saying PlatformIO is installed. 
Can I use Deviot now? Or do I have to change directories elsewhere too?

Thank You!

**Comment by gepd** [comment]
You should be able to use Deviot now, but if you find any problem post it here to fix it!

**Comment by Suyash458** [comment]
Great, thanks again! I'll close this for now.
