### ISSUE TITLE
Checkbox for Use PlatformIO Structure menu option

### ISSUE THREAD

**Issue by jwhendy** [gepd/Deviot#166]
In [this post](https://github.com/gepd/Deviot/issues/137#issuecomment-318223622) of #137 the `Use PlatformIO Structure` option shows a checkbox. I didn't have this on my system... I did find that changing `presets/main_menu.json` adds it:
```
                               {
                                    "caption":"menu_always_native",
                                    "checkbox":true,
                                    "command":"deviot_pio_structure"
                                },
```

 Any reason not to have one? Since the behavior is quite different (build dir, where the `.ino` file lives), I think knowing which setting is active would be helpful. I can submit a PR since I already did it; you can decline it if I don't understand why you don' currently have this.

**Comment by gepd** [comment]
I should have missed that, do the checkbox work after you added `"checkbox":true`?

**Comment by jwhendy** [comment]
Indeed!

As is:
![2017-09-07_202940](https://user-images.githubusercontent.com/379357/30192196-b3e44e7c-940b-11e7-8887-a4d11d3dcd6b.png)

With `"checkbox":true`, unchecked:
![2017-09-07_203102](https://user-images.githubusercontent.com/379357/30192207-c491f2ce-940b-11e7-9a2a-c91eb81b7c30.png)

Checked:
![2017-09-07_202329](https://user-images.githubusercontent.com/379357/30192119-09af6158-940b-11e7-8595-026ba7c618ca.png)

Quick tests suggest the behavior works (checked, uses pio structure, unchecked doesn't) and it also stays consistent between shutdown/restart (persists).

**Comment by gepd** [comment]
I haven't noted this because on windows it has a diffent behavior, I've accepted the PR

Thanks!

**Comment by jwhendy** [comment]
I think the screenshot I saw was on Windows actually... it looked like a great thing to have and so I just had to see how it was working with other options that use it. Happy to help!
