### ISSUE TITLE
DEV Serial options greyed out

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#182]
Serial options

`Clean Monitor View`
and 
`Send`
are greyed out for me.

**Comment by gepd** [comment]
That options are only available when the monitor serial is running.
In your case it's greyed out while the monitor is running?

**Comment by tablatronix** [comment]
It was running, 

its working now, It must have been stuck in some condition where it thought it was not.

I will see if it happens again, might have been a fluke related to the other error uploading and how it stops the serial monitor

**Comment by gepd** [comment]
It could be, when you are running the Monitor Serial and your upload fails, it wont start again automatically

**Comment by tablatronix** [comment]
yeah i know same with compile fail
#171

**Comment by gepd** [comment]
It shouldn't happen at compile, because the compilation doesn't use the serial port. At least with the upload, it's programed to work that way. The other could be a bug
