### ISSUE TITLE
dev platformio.ini upload speed whitespace parsing failure, fatal

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#189]
osx

deviot parses platformio.ini incorrectly and inserts newlines if upload_speed does not contain spaces around `=`

```
[env:normal_1024]
board = esp12e
upload_speed=460800
```

after compile, file gets touched and reformated ( even with overwrite upload speed off )

```
[env:normal_1024]
board =
esp12e
upload_speed=460800
```

**Comment by gepd** [comment]
Fixed
