### ISSUE TITLE
Deviot doesn't upload - Error 1

### ISSUE THREAD

**Issue by Scartoug** [gepd/Deviot#191]
Deviot doesn't upload my sketch  causing error 1

<pre><code>[ Deviot 2.2.0-dev.10 ] Starting...
[10/15/17 23:07:32] Processing uno (upload_protocol: stk500v2; platform: atmelavr; upload_flags: -Pusb; board: uno; framework: arduino)
Verbose mode can be enabled via `-v, --verbose` option
Converting Bli2nk.ino
Collected 24 compatible libraries
Looking for dependencies...
Project does not have dependencies
Compiling .pioenvs\uno\src\Bli2nk.ino.o
Archiving .pioenvs\uno\libFrameworkArduinoVariant.a
Compiling .pioenvs\uno\FrameworkArduino\CDC.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial0.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial1.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial2.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial3.o
Compiling .pioenvs\uno\FrameworkArduino\IPAddress.o
Compiling .pioenvs\uno\FrameworkArduino\PluggableUSB.o
Compiling .pioenvs\uno\FrameworkArduino\Print.o
Compiling .pioenvs\uno\FrameworkArduino\Stream.o
Compiling .pioenvs\uno\FrameworkArduino\Tone.o
Compiling .pioenvs\uno\FrameworkArduino\USBCore.o
Compiling .pioenvs\uno\FrameworkArduino\WInterrupts.o
Compiling .pioenvs\uno\FrameworkArduino\WMath.o
Compiling .pioenvs\uno\FrameworkArduino\WString.o
Compiling .pioenvs\uno\FrameworkArduino\_wiring_pulse.o
Compiling .pioenvs\uno\FrameworkArduino\abi.o
Compiling .pioenvs\uno\FrameworkArduino\hooks.o
Compiling .pioenvs\uno\FrameworkArduino\main.o
Compiling .pioenvs\uno\FrameworkArduino\new.o
Compiling .pioenvs\uno\FrameworkArduino\wiring.o
Compiling .pioenvs\uno\FrameworkArduino\wiring_analog.o
Compiling .pioenvs\uno\FrameworkArduino\wiring_digital.o
Compiling .pioenvs\uno\FrameworkArduino\wiring_pulse.o
Compiling .pioenvs\uno\FrameworkArduino\wiring_shift.o
Archiving .pioenvs\uno\libFrameworkArduino.a
Linking .pioenvs\uno\firmware.elf
Checking program size
text	   data	    bss	    dec	    hex	filename
2224	     22	    168	   2414	    96e	.pioenvs\uno\firmware.elf
Building .pioenvs\uno\firmware.hex
Looking for upload port...
Programming .pioenvs\uno\firmware.hex
avrdude done.  Thank you.
*** [program] Error 1
 [ERROR] Took 3.74 seconds 
</code></pre>

**Comment by Scartoug** [comment]
> [ Deviot 2.2.0-dev.10 ] Starting...
[10/15/17 23:07:32] Processing uno (upload_protocol: stk500v2; platform: atmelavr; upload_flags: -Pusb; board: uno; framework: arduino)
Verbose mode can be enabled via `-v, --verbose` option
Converting Bli2nk.ino
Collected 24 compatible libraries
Looking for dependencies...
Project does not have dependencies
Compiling .pioenvs\uno\src\Bli2nk.ino.o
Archiving .pioenvs\uno\libFrameworkArduinoVariant.a
Compiling .pioenvs\uno\FrameworkArduino\CDC.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial0.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial1.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial2.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial3.o
Compiling .pioenvs\uno\FrameworkArduino\IPAddress.o
Compiling .pioenvs\uno\FrameworkArduino\PluggableUSB.o
Compiling .pioenvs\uno\FrameworkArduino\Print.o
Compiling .pioenvs\uno\FrameworkArduino\Stream.o
Compiling .pioenvs\uno\FrameworkArduino\Tone.o
Compiling .pioenvs\uno\FrameworkArduino\USBCore.o
Compiling .pioenvs\uno\FrameworkArduino\WInterrupts.o
Compiling .pioenvs\uno\FrameworkArduino\WMath.o
Compiling .pioenvs\uno\FrameworkArduino\WString.o
Compiling .pioenvs\uno\FrameworkArduino\_wiring_pulse.o
Compiling .pioenvs\uno\FrameworkArduino\abi.o
Compiling .pioenvs\uno\FrameworkArduino\hooks.o
Compiling .pioenvs\uno\FrameworkArduino\main.o
Compiling .pioenvs\uno\FrameworkArduino\new.o
Compiling .pioenvs\uno\FrameworkArduino\wiring.o
Compiling .pioenvs\uno\FrameworkArduino\wiring_analog.o
Compiling .pioenvs\uno\FrameworkArduino\wiring_digital.o
Compiling .pioenvs\uno\FrameworkArduino\wiring_pulse.o
Compiling .pioenvs\uno\FrameworkArduino\wiring_shift.o
Archiving .pioenvs\uno\libFrameworkArduino.a
Linking .pioenvs\uno\firmware.elf
Checking program size
text	   data	    bss	    dec	    hex	filename
2224	     22	    168	   2414	    96e	.pioenvs\uno\firmware.elf
Building .pioenvs\uno\firmware.hex
Looking for upload port...
Programming .pioenvs\uno\firmware.hex
avrdude done.  Thank you.
*** [program] Error 1
 [ERROR] Took 3.74 seconds 

>

**Comment by gepd** [comment]
Are you using an arduino uno?
Have you tried to upload the same sketch with the Arduino IDE?

**Comment by Scartoug** [comment]
I'm using an Arduino UNO and my sketch can be uploaded through Arduino IDE, working

**Comment by gepd** [comment]
Please follow [this](https://github.com/gepd/Deviot/wiki/Setup#developer) steps to install the develop version in the status bar you should see `Deviot 2.2.0-dev.10`

Then activate the verbose output from `Deviot Menu > Options > Full Verbose Output When Building`

After this, try to upload your sketch again. This time the output should have more information, paste that info here.

**Comment by Ben-Lichtman** [comment]
I am getting a similar issue with error 1

Here is the verbose output of upload:

[ Deviot 2.2.0-dev.11 ] Starting...
[Tue Nov 21 21:38:48 2017] Processing megaatmega2560 (upload_protocol: stk500v1; framework: arduino; upload_flags: -P$UPLOAD_PORT; platform: atmelavr; board: megaatmega2560; upload_port: /dev/tty.usbmodem1411)
--------------------------------------------------------------------------------
avr-g++ -o "/Users/ben/Desktop/Sensor/project.ino.cpp" -x c++ -fpreprocessed -dD -E "/var/folders/h_/ck8vd1ln5jj2r5y8wyfs7vc40000gn/T/tmp0uA9rv"
Collected 41 compatible libraries
Looking for dependencies...
Project does not have dependencies
avr-g++ -o .pioenvs/megaatmega2560/src/project.ino.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega -I/Users/ben/Desktop/Sensor /Users/ben/Desktop/Sensor/project.ino.cpp
avr-gcc-ar rc .pioenvs/megaatmega2560/libFrameworkArduinoVariant.a
avr-gcc-ranlib .pioenvs/megaatmega2560/libFrameworkArduinoVariant.a
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/CDC.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/CDC.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial0.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial0.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial1.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial1.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial2.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial2.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial3.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial3.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/IPAddress.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/IPAddress.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/PluggableUSB.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/PluggableUSB.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/Print.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/Print.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/Stream.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/Stream.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/Tone.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/Tone.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/USBCore.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/USBCore.cpp
avr-gcc -o .pioenvs/megaatmega2560/FrameworkArduino/WInterrupts.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/WInterrupts.c
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/WMath.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/WMath.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/WString.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/WString.cpp
avr-gcc -x assembler-with-cpp -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega -c -o .pioenvs/megaatmega2560/FrameworkArduino/_wiring_pulse.o /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/_wiring_pulse.S
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/abi.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/abi.cpp
avr-gcc -o .pioenvs/megaatmega2560/FrameworkArduino/hooks.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/hooks.c
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/main.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/main.cpp
avr-g++ -o .pioenvs/megaatmega2560/FrameworkArduino/new.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/new.cpp
avr-gcc -o .pioenvs/megaatmega2560/FrameworkArduino/wiring.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/wiring.c
avr-gcc -o .pioenvs/megaatmega2560/FrameworkArduino/wiring_analog.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_analog.c
avr-gcc -o .pioenvs/megaatmega2560/FrameworkArduino/wiring_digital.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_digital.c
avr-gcc -o .pioenvs/megaatmega2560/FrameworkArduino/wiring_pulse.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_pulse.c
avr-gcc -o .pioenvs/megaatmega2560/FrameworkArduino/wiring_shift.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega2560 -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_MEGA2560 -DARDUINO=10619 -I/Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino -I/Users/ben/.platformio/packages/framework-arduinoavr/variants/mega /Users/ben/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_shift.c
avr-gcc-ar rc .pioenvs/megaatmega2560/libFrameworkArduino.a .pioenvs/megaatmega2560/FrameworkArduino/CDC.o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial.o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial0.o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial1.o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial2.o .pioenvs/megaatmega2560/FrameworkArduino/HardwareSerial3.o .pioenvs/megaatmega2560/FrameworkArduino/IPAddress.o .pioenvs/megaatmega2560/FrameworkArduino/PluggableUSB.o .pioenvs/megaatmega2560/FrameworkArduino/Print.o .pioenvs/megaatmega2560/FrameworkArduino/Stream.o .pioenvs/megaatmega2560/FrameworkArduino/Tone.o .pioenvs/megaatmega2560/FrameworkArduino/USBCore.o .pioenvs/megaatmega2560/FrameworkArduino/WInterrupts.o .pioenvs/megaatmega2560/FrameworkArduino/WMath.o .pioenvs/megaatmega2560/FrameworkArduino/WString.o .pioenvs/megaatmega2560/FrameworkArduino/_wiring_pulse.o .pioenvs/megaatmega2560/FrameworkArduino/abi.o .pioenvs/megaatmega2560/FrameworkArduino/hooks.o .pioenvs/megaatmega2560/FrameworkArduino/main.o .pioenvs/megaatmega2560/FrameworkArduino/new.o .pioenvs/megaatmega2560/FrameworkArduino/wiring.o .pioenvs/megaatmega2560/FrameworkArduino/wiring_analog.o .pioenvs/megaatmega2560/FrameworkArduino/wiring_digital.o .pioenvs/megaatmega2560/FrameworkArduino/wiring_pulse.o .pioenvs/megaatmega2560/FrameworkArduino/wiring_shift.o
avr-gcc-ranlib .pioenvs/megaatmega2560/libFrameworkArduino.a
avr-g++ -o .pioenvs/megaatmega2560/firmware.elf -Os -mmcu=atmega2560 -Wl,--gc-sections -flto -fuse-linker-plugin .pioenvs/megaatmega2560/src/project.ino.o -L.pioenvs/megaatmega2560 -Wl,--start-group .pioenvs/megaatmega2560/libFrameworkArduinoVariant.a .pioenvs/megaatmega2560/libFrameworkArduino.a -lm -Wl,--end-group
Checking program size
text	   data	    bss	    dec	    hex	filename
1930	     26	    166	   2122	    84a	.pioenvs/megaatmega2560/firmware.elf
avr-objcopy -O ihex -R .eeprom .pioenvs/megaatmega2560/firmware.elf .pioenvs/megaatmega2560/firmware.hex
BeforeUpload(["program"], [".pioenvs/megaatmega2560/firmware.hex"])
avrdude -v -p atmega2560 -C /Users/ben/.platformio/packages/tool-avrdude/avrdude.conf -c stk500v1 -P/dev/tty.usbmodem1411 -U flash:w:.pioenvs/megaatmega2560/firmware.hex:i
avrdude: Version 6.3, compiled on Jan 17 2017 at 12:01:35
Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
Copyright (c) 2007-2014 Joerg Wunsch
System wide configuration file is "/Users/ben/.platformio/packages/tool-avrdude/avrdude.conf"
User configuration file is "/Users/ben/.avrduderc"
User configuration file does not exist or is not a regular file, skipping
Using Port                    : /dev/tty.usbmodem1411
Using Programmer              : stk500v1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x00
avrdude done.  Thank you.
*** [program] Error 1
========================== [ERROR] Took 53.28 seconds ==========================

Build works fine, and I have the correct board selected. I have also tried this on the dev branch, same thing.

**Comment by gepd** [comment]
re-open if you keep with this issue
