### ISSUE TITLE
Serial Monitor doesn't show up

### ISSUE THREAD

**Issue by werofuentes** [gepd/Deviot#196]
Windows 7 Home x64

Arduino Mega 2560

I just install Deviot on Sublime Text, it works almost perfect, i only have one problem, i can`t open the serial monitor.

**Comment by gepd** [comment]
please, paste here the ouput of the ST console (`View > Show console`) after start the Serial Monitor

**Comment by werofuentes** [comment]
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Wero/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Wero/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Wero/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.893785
font face "Monaco" has different widths for bold characters, disabling to prevent text reflow
startup time: 0.931785
first paint time: 0.932785
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin All Autocomplete.all_views_completions
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin ayu.activation
reloading plugin ayu.Icons
reloading plugin Boxy Theme.BT
reloading plugin Boxy Theme.Icons
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Browser Refresh.BrowserRefresh
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin CSS Unminifier.CssUnminifier
reloading plugin Emmet.emmet-plugin
reloading plugin HTML Nest Comments.HTMLNestComments
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Materialize.Materialize
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin php-snippets.plugin
reloading plugin Sass-Director.sass-director
reloading plugin SassBeautify.SassBeautify
reloading plugin SassSolution.main
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin CodeFormatter.CodeFormatter
CodeFormatter: formatting python files on ST3 not supported.
reloading plugin ColorPicker.sublimecp
reloading plugin DA UI.DA UI
reloading plugin Deviot-develop.Deviot
reloading plugin Gulp.base_command
reloading plugin Gulp.caches
reloading plugin Gulp.cross_platform_codecs
reloading plugin Gulp.cross_platform_process
reloading plugin Gulp.dir_context
reloading plugin Gulp.event_task
reloading plugin Gulp.gulp
reloading plugin Gulp.gulp_version
reloading plugin Gulp.hasher
reloading plugin Gulp.insert_in_output_view
reloading plugin Gulp.plugins
reloading plugin Gulp.progress_notifier
reloading plugin Gulp.settings
reloading plugin Gulp.timeout
reloading plugin JavaScript Completions._generated_2017_04_09_at_16_06_42
reloading plugin JavaScript Completions.reloader
reloading plugin LiveReload.__init__
reloading plugin LiveReload.CoffeescriptPlugin
reloading plugin LiveReload.CommandAPI
reloading plugin LiveReload.CompassPlugin
reloading plugin LiveReload.LESSPlugin
reloading plugin LiveReload.LiveReload
reloading plugin LiveReload.SimpleReloadCallback
reloading plugin LiveReload.SimpleReloadPlugin
reloading plugin LiveReload.SimpleReloadPluginDelay
reloading plugin LiveReload.SimpleWSCallback
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin Terminal.Terminal
plugins loaded
CodeFormatter: Plugin Initialized
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "main in C:\Users\Wero\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 606, in plugin_loaded
  File "main in C:\Users\Wero\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 305, in init
  File "main in C:\Users\Wero\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 100, in __init__
  File "gutter_icons_color_highlighter in C:\Users\Wero\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 104, in check
  File "gutter_icons_color_highlighter in C:\Users\Wero\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 113, in _create_icon
  File "gutter_icons_color_highlighter in C:\Users\Wero\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 119, in _run_command
  File "./python3.3/subprocess.py", line 784, in __init__
  File "./python3.3/subprocess.py", line 980, in _get_handles
  File "./python3.3/subprocess.py", line 1030, in _make_inheritable
OSError: [WinError 6] Controlador no válido
LiveReload: added file /livereload.js with content-type: text/javascript
INFO:WebSocketClient:Starting server
Emmet: No need to update PyV8
reloading settings Packages/User/deviot.sublime-settings
Exception in thread DownloadCanIuseJsonData:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\Wero\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_generated_2017_04_09_at_16_06_42.py", line 781, in donwload_can_i_use_json_data
    os.remove(path_to_test_can_i_use_data)
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\Users\\Wero\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Completions\\helper\\can_i_use\\can_i_use_data2.json'

Package Control: Skipping automatic upgrade, last run at 2017-10-31 17:25:45, next run at 2017-10-31 18:25:45 or after
reloading settings Packages/User/deviot.sublime-settings
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "C:\Users\Wero\AppData\Roaming\Sublime Text 3\Packages\Deviot-develop\commands\deviot_toggle_serial_monitor.py", line 6, in run
    serial.toggle_serial_monitor()
  File "C:\Users\Wero\AppData\Roaming\Sublime Text 3\Packages\Deviot-develop\libraries\serial.py", line 293, in toggle_serial_monitor
    serial_monitor = get_serial_monitor(port_id)
  File "C:\Users\Wero\AppData\Roaming\Sublime Text 3\Packages\Deviot-develop\libraries\serial.py", line 282, in get_serial_monitor
    serial_monitor = SerialMonitor(port_id)
  File "C:\Users\Wero\AppData\Roaming\Sublime Text 3\Packages\Deviot-develop\libraries\serial.py", line 52, in __init__
    self.serial = pyserial.Serial()
  File "C:\Users\Wero\AppData\Roaming\Sublime Text 3\Packages\Deviot-develop\libraries\pyserial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\Wero\AppData\Roaming\Sublime Text 3\Packages\Deviot-develop\libraries\pyserial\serialutil.py", line 229, in __init__
    self.exclusive = exclusive
  File "C:\Users\Wero\AppData\Roaming\Sublime Text 3\Packages\Deviot-develop\libraries\pyserial\serialwin32.py", line 475, in exclusive
    serial.SerialBase.exclusive.__set__(self, exclusive)
NameError: global name 'serial' is not defined

That's all.
Actually, i just noticed something weird, when i started sublime text, i clicked the button to start the serial monitora and it worked, but then, i compiled something just to check out and started again the serial monitor but this time didn't work.

**Comment by gepd** [comment]
Please replace the current files of the plugin by [this](https://github.com/gepd/Deviot/archive/hotfix/linux_serial.zip) and let me know if you keep seeing the errors, I hope to merge that changes this week to solve this problem

**Comment by werofuentes** [comment]
I tried what you say, but still the same. 
By the way, thank you.

**Comment by gepd** [comment]
It's the exactly the same error? if that is the case, maybe the plugin wasn't update, it has a new code so the error should be different. If it's different please paste here to upload a new patch

You're welcome!

**Comment by werofuentes** [comment]
Yeah, the same, i forgot to mention something, the link with the zip that you gave me, i had already replace it with the original, i had the problem about the serial port as well, but with that zip you fixed it.

**Comment by gepd** [comment]
I've pushed a change today to fix other problems in that branch, replacing the files again should fix the problem, same as: https://github.com/gepd/Deviot/issues/195

**Comment by werofuentes** [comment]
Wow, awesome, now it works, thanks a lot @gepd, you made a great work, keep it up.

**Comment by jostidetosti** [comment]
My issues ( #195) are resolved. Everything works and no errors in console.

**Comment by gepd** [comment]
Thanks both for the report, I'll let this open until I merge it into master branch

**Comment by gepd** [comment]
fix merged in the developer branch.

Re-open it if you have the same issue
