### ISSUE TITLE
Dev mutiple boards showing up some with asterisks ?

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#197]
When I click select board
type nodemcu
I see double of everything.

I assume this is because I have 2 esp8266 enviroments installed ?
One shows `* nodemcu`
Do you know what this means ?

**Comment by gepd** [comment]
Yes, I've documented that feature here: https://github.com/gepd/Deviot/wiki/Deviot-Menu#select-board

**Comment by tablatronix** [comment]
Sorry, ill RTFM. heh
