### ISSUE TITLE
fatal error: twi.h: No such file or directory

### ISSUE THREAD

**Issue by jostidetosti** [gepd/Deviot#198]
Kubuntu 17.10
Arduino Uno

Code compiles fine in Arduino IDE, but not with Deviot. Error: 

> fatal error: twi.h: No such file or directory

No errors in ST Console.

Code:

```
#include <Wire.h>

void setup(){}

void loop(){}
```

**Comment by gepd** [comment]
Can you try putting your sketch in a empty folder and try again.

Let me know if that works

**Comment by jostidetosti** [comment]
Same result.

**Comment by gepd** [comment]
Activate the option `Deviot > Options > Full Verbose Output` and compile again, it should display extra information in th deviot console, paste that info here. If you see the same info, restart ST and try again

**Comment by jostidetosti** [comment]
`
[ Deviot 2.1.6 ] Starting...
[Thu Nov 16 10:04:13 2017] Processing uno (platform: atmelavr; lib_extra_dirs: /home/username/Programs/arduino-1.8.4/libraries; board: uno; framework: arduino)
--------------------------------------------------------------------------------
avr-g++ -o "/home/username/Code/Arduino/twitest/twitest.ino.cpp" -x c++ -fpreprocessed -dD -E "/tmp/tmpqiUdtH"
Collected 87 compatible libraries
Looking for dependencies...
Library Dependency Graph
|-- <Wire> v1.0 (/home/username/.platformio/lib/Wire)
avr-g++ -o .pioenvs/uno/src/twitest.ino.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard -I/home/username/Code/Arduino/twitest -I/home/username/.platformio/lib/Wire /home/username/Code/Arduino/twitest/twitest.ino.cpp
avr-gcc-ar rc .pioenvs/uno/libFrameworkArduinoVariant.a
avr-gcc-ranlib .pioenvs/uno/libFrameworkArduinoVariant.a
avr-g++ -o .pioenvs/uno/FrameworkArduino/CDC.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/CDC.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial0.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial0.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial1.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial1.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial2.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial2.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/HardwareSerial3.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/HardwareSerial3.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/IPAddress.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/IPAddress.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/PluggableUSB.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/PluggableUSB.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/Print.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/Print.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/Stream.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/Stream.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/Tone.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/Tone.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/USBCore.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/USBCore.cpp
avr-gcc -o .pioenvs/uno/FrameworkArduino/WInterrupts.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/WInterrupts.c
avr-g++ -o .pioenvs/uno/FrameworkArduino/WMath.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/WMath.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/WString.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/WString.cpp
avr-gcc -x assembler-with-cpp -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard -c -o .pioenvs/uno/FrameworkArduino/_wiring_pulse.o /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/_wiring_pulse.S
avr-g++ -o .pioenvs/uno/FrameworkArduino/abi.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/abi.cpp
avr-gcc -o .pioenvs/uno/FrameworkArduino/hooks.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/hooks.c
avr-g++ -o .pioenvs/uno/FrameworkArduino/main.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/main.cpp
avr-g++ -o .pioenvs/uno/FrameworkArduino/new.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/new.cpp
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/wiring.c
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring_analog.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_analog.c
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring_digital.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_digital.c
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring_pulse.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_pulse.c
avr-gcc -o .pioenvs/uno/FrameworkArduino/wiring_shift.o -c -std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard /home/username/.platformio/packages/framework-arduinoavr/cores/arduino/wiring_shift.c
avr-g++ -o .pioenvs/uno/lib/Wire/Wire.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619 -I/home/username/.platformio/packages/framework-arduinoavr/cores/arduino -I/home/username/.platformio/packages/framework-arduinoavr/variants/standard -I/home/username/.platformio/lib/Wire /home/username/.platformio/lib/Wire/Wire.cpp
/home/username/.platformio/lib/Wire/Wire.cpp:30:17: fatal error: twi.h: No such file or directory
#include "twi.h"
^
compilation terminated.
*** [.pioenvs/uno/lib/Wire/Wire.o] Error 1
========================== [ERROR] Took 0.77 seconds ==========================
`

**Comment by gepd** [comment]
If you had this problem yet, please try this:

Go to `Deviot Menu > Show Terminal` and write `pio update` 

It should update all platforms and tools in your setup. 

`/home/username/.platformio/lib/Wire/Wire.cpp:30:17: fatal error: twi.h: No such file or directory
#include "twi.h"`

This line make me believe it's a problem with the framework

If the problem continues, remove the folder in `~/platformio` it will remove all the platforms, frameworks and tools installed by PIO, restart ST and try to campile again, it should install all neccesary files again

**Comment by m-chichikalov** [comment]
If that said Gepd does not help, try to change  #include "twi.h"  for   #include <twi.h>

**Comment by jostidetosti** [comment]
Removing all folders in ~/platformio did the trick. Thanks!
