### ISSUE TITLE
Support for MKR1000

### ISSUE THREAD

**Issue by javorosas** [gepd/Deviot#20]
I just installed support for SAMD arduino boards, like the new MKR1000, from the boards manager of the Arduino IDE. I wonder how can I set Sublime/Deviot to work with the MKR1000

Thanks :)

**Comment by gepd** [comment]
I've asked the state to support SAMD boards to the [platformio team](https://github.com/platformio/platformio/issues) (the core of deviot) we should have an answer soon

**Comment by tabchas** [comment]
How can we use the development version of platformio? The issue apparently has been fixed as of today, but I couldn't find where we could use the develop version of platforimio in Deviot.

Here is link to SAMD issue at PlatformIO: https://github.com/platformio/platformio/issues/520#issuecomment-223125607

**Comment by gepd** [comment]
Today platformio released a new version supporting the MKR1000 board, please update platformio from `Deviot menu > Options > Update platformio`

**Comment by javorosas** [comment]
Awesome!
