### ISSUE TITLE
'Use development PIO version' doesn't seem to (want 3.5.0b6, get 3.4.1)

### ISSUE THREAD

**Issue by John-Titor** [gepd/Deviot#201]
I have PIO installed via the VS code plugin, which got me PIO core 3.5.0b6.

With Deviot, it looks like 3.4.1 is the most recent PIO core available (at least, selecting 'use development Pio version' and 'upgrade PlatformIO' doesn't get me anything more recent.

**Comment by gepd** [comment]
I've updated deviot to `v2.2.0-dev.12` with a fix for this issue, let me know if it fixed your problem

Make sure to have installed the [developer](https://github.com/gepd/Deviot/wiki/Setup#developer) version

**Comment by John-Titor** [comment]
Looks good; that got me PIO 3.5.0rc2, which makes everything else happy.
