### ISSUE TITLE
Sketch won't compile if current buffer is a header (.h)

### ISSUE THREAD

**Issue by John-Titor** [gepd/Deviot#202]
If you have a sketch containing a .h file, and you ask Deviot to build your sketch while that file is current, building fails with:

> [ Deviot 2.1.6 ] Starting...
> 20:52:57 filename.h is not an IoT File

It works correctly if any .cpp or .ino file in the sketch is selected.

**Comment by m-chichikalov** [comment]
I saw some strange behavior when .cpp file of library was chosen (was an active in ST). It starts create the pio folder structure inside 'lib' folder.

**Comment by gepd** [comment]
I've added the `h` extension to the list of accepted files, you shouldn't have problem now

**Comment by John-Titor** [comment]
Seems to work, thanks!
