### ISSUE TITLE
examples hard to navigate

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#205]
Ever since you added the quick menu for examples, I find it hard to navigate them, the tree was much nicer for browsing trees, but I think this can be mitigated by adding `up one level`.

quick menu is nice for most menu control , but it sucks for trees, sometimes you need to see the entire tree and jump around alot. Just a thought.

**Comment by gepd** [comment]
Fixed in `dev.14` re-open if you find any problem
