### ISSUE TITLE
serial monitor does not print NULL

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#215]
Serial.println("NULL");

Serial prints blank

I spent like 2 hours debugging something because of this, doh

**Comment by tablatronix** [comment]
`        text = text.replace('\r', '').replace('NULL', '')`

**Comment by gepd** [comment]
Sorry about that, I think it's an old Stino code.

Fixed in: https://github.com/gepd/Deviot/commit/e2e277654b9725fa9165beca2d2d04d38f720777
