### ISSUE TITLE
upgrade platformio

### ISSUE THREAD

**Issue by thewilloftheshadow** [gepd/Deviot#220]
When i try to upgrade platformio, i get this. i have reinstalled deviot and nothing happened...
![image](https://user-images.githubusercontent.com/35580099/38759539-09a3efb2-3f3c-11e8-99ec-24a5c83ad64a.png)

**Comment by gepd** [comment]
Did Deviot show you any error during the setup?

**Comment by thewilloftheshadow** [comment]
no i have no errors on setup. i run windows 10 home and sublime text 3

**Comment by gepd** [comment]
Please go to: `Packages\User\Deviot` and copy here the content of the `deviot.ini` file

**Comment by thewilloftheshadow** [comment]
i do not see a deviot.ini file under C:\Users\MYUSERNAME\AppData\Roaming\Sublime Text 3\Packages\Deviot (Arduino IDE)

**Comment by thewilloftheshadow** [comment]
[config]
last_action = 2
env_path = C:\Users\willi\AppData\Roaming\Sublime Text 3\Packages\User\Deviot\penv;C:\Users\willi\AppData\Roaming\Sublime Text 3\Packages\User\Deviot\penv\Scripts;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\VHStoDVD\DLLShared\;C:\Users\willi\AppData\Local\Microsoft\WindowsApps;
installed = True
last_check_update = 2018-04-17 16:04:26.859297

**Comment by gepd** [comment]
Can you check if you have any file here: `C:\Users\willi\AppData\Roaming\Sublime Text 3\Packages\User\Deviot\penv\Scripts` If not can you open a terminal window and run `platformio --version` and tell me if you get any output

**Comment by thewilloftheshadow** [comment]
i have these files:
![image](https://user-images.githubusercontent.com/35580099/38822377-e2fa3806-4168-11e8-8757-ff994342a4b8.png)

**Comment by thewilloftheshadow** [comment]
![sublime-error](https://user-images.githubusercontent.com/35580099/41247114-a369667c-6d72-11e8-996f-1ce7cdee3350.PNG)

**Comment by thewilloftheshadow** [comment]
won't install either the main or dev versions of platformio and i get this message a lot

**Comment by thewilloftheshadow** [comment]
any update on this?
