### ISSUE TITLE
How to add snippets for devion on sublime?

### ISSUE THREAD

**Issue by Encarnacao** [gepd/Deviot#23]

**Comment by gepd** [comment]
As is described in [this document](http://sublimetext.info/docs/en/extensibility/snippets.html) of ST 
You only need to make sure to let the scope line as:

`<scope>source.deviot</scope>`

**Comment by Encarnacao** [comment]
i have tried with
<scope>source.deviot</scope> and dint work

it did work with
<scope>source.iot</scope>

**Comment by gepd** [comment]
Sorry about that @Encarnacao I didn't check it twice as you said it with `source.iot`

I'll add all the stino snippets availables to deviot, the new release with all the changes will be released this or next week :)

**Comment by gepd** [comment]
I've released a new version with 64 snippets
