### ISSUE TITLE
FEATURE install lib interactive show more info

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#242]
platformio library manager can contains duplicate names

Deviot uses interactive and shows you both, but they look exactly the same

Maybe show "authors" in drop down to show forks.

**Comment by tablatronix** [comment]
eg.

`max6675`

**Comment by gepd** [comment]
I've pushed a change adding the author(s) name after the library name and the library description, let me know what do you think

**Comment by tablatronix** [comment]
Looking great
