### ISSUE TITLE
RU lang

### ISSUE THREAD

**Issue by R4ddd** [gepd/Deviot#248]
Переведен с Английской версии.
не уверенный перевод обозначен ?****? 
типа: msgstr "?Там была ошибка?\n"
 
переименовать в ru.lang и положить в \Sublime Text Build ***\Data\Packages\Deviot (Deviot-develop)\languages\
если желаете, положите в репозитарий.

Translated from the English version.
not sure translation is indicated  ? ****?
type: msgid "? Was there an error? \ n"
 
rename it to ru.lang and put it in \ Sublime Text Build *** \ Data \ Packages \ Deviot (or Deviot-develop) \ languages \
if you wish, put it in the repository.
[ru.txt](https://github.com/gepd/Deviot/files/2209314/ru.txt)

**Comment by gepd** [comment]
Thanks @R4ddd I've added it to the develop branch
