### ISSUE TITLE
feature: sort examples

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#251]
sort examples somehow, they are in no particular order atm.

**Comment by gepd** [comment]
will alphabetically be enoght?

**Comment by tablatronix** [comment]
I think so

**Comment by gepd** [comment]
Done

In https://github.com/gepd/Deviot/commit/91ca7cabd815825805adf93ad68db5181ddfc2d0 I've also added new info in the examples list, some platform can have the same example for different boards, now you  can identify it
