### ISSUE TITLE
UI: "Hide Terminal" adds new monitor pane

### ISSUE THREAD

**Issue by fiveangle** [gepd/Deviot#255]
### Operating system
Windows 10
### Description of problem
Selecting "Hide Terminal" adds an additional window pane
### Steps to Reproduce
Select "Hide Terminal", observe terminal open in split pane
Continue to select "Hide Terminal" and observe additional terminal split panes created

Screen capture of process:
https://www.screencast.com/t/wTTJOtCIemy

**Comment by gepd** [comment]
I've just push a fix for this issue please let me know if now work as it's expected

**Comment by fiveangle** [comment]
Yep, works !

Thanks !

-=dave

**Comment by Perlovka** [comment]
Still have this issue on Linux with 2.2.1 version.

**Comment by gepd** [comment]
Are you using the develop branch?

**Comment by Perlovka** [comment]
> Are you using the develop branch?

No, just installed from Sublime Text 3. Maybe it's time to release new version? =)
