### ISSUE TITLE
[Suggestion] Only upload if build succeeded

### ISSUE THREAD

**Issue by OoDeLally** [gepd/Deviot#256]
### Operating system
Linux Mint
### Board used
Arduino Uno
### Description of problem

Rather a suggestion. Is it possible to only upload the program if the build succeeded?
Build log lines are scrolling very fast, and it is hard to know if my board is running the new successfully-built code I've just modified, or the old code from the last successful build in the case my new code failed to build.

**Comment by gepd** [comment]
Currently that is the way how it works, if the compilation fails it won't upload the firmware, you will see the fail state at the end of the console
