### ISSUE TITLE
Login into platformio account from deviot

### ISSUE THREAD

**Issue by krish2487** [gepd/Deviot#290]
### Operating system : 
Macos Mojave

### Board used: 
NA

### Description of problem :
How to login into platformio account using deviot.

### Error(s) in ST Console : 
NA

### Steps to Reproduce : 
1. Menu > Deviot > Show Terminal
2. Enter "pio account login"
3. Enter email address

### Actual Results : 
Receive invalid command error

### Expected Results:
I expect to be able to enter my email address and password and login into the pio account.

### Additional info
Screenshots of the issue.

![Screenshot 2019-05-24 at 15 58 16 (2)](https://user-images.githubusercontent.com/23363406/58333336-7d315280-7e3d-11e9-83ce-12185e47c82d.png)
![Screenshot 2019-05-24 at 15 58 19 (2)](https://user-images.githubusercontent.com/23363406/58333337-7d315280-7e3d-11e9-856c-ba39a9d43627.png)
![Screenshot 2019-05-24 at 15 58 34 (2)](https://user-images.githubusercontent.com/23363406/58333338-7d315280-7e3d-11e9-9ddd-dbedc2604fa3.png)
![Screenshot 2019-05-24 at 15 58 49 (2)](https://user-images.githubusercontent.com/23363406/58333339-7d315280-7e3d-11e9-844b-be0fa14a1ffc.png)
![Screenshot 2019-05-24 at 15 59 10 (2)](https://user-images.githubusercontent.com/23363406/58333340-7dc9e900-7e3d-11e9-86be-26fa77967c8b.png)

**Comment by gepd** [comment]
I'll improve this when you use only `platformio account login`, for now you do `platformio account login -u email@email.com -p password `

**Comment by krish2487** [comment]
@gepd Thank you the suggestion. unfortunately it does not seem to work.
This is what I get when I try logging in using the method above.

![Screenshot 2019-06-01 at 09 57 11](https://user-images.githubusercontent.com/23363406/58745685-1a9b1080-8454-11e9-82aa-a6ed46055f08.png)

**Comment by gepd** [comment]
I had the same problem, what I did was install the developer version of platformio:

1. uninstall existing version
`pip uninstall platformio`


2. install the latest development version of PlatformIO
`pip install -U https://github.com/platformio/platformio-core/archive/develop.zip`

Currently I'm using `PlatformIO, version 4.0.0a16` you can check this with `platformio --version`

**Comment by krish2487** [comment]
That worked!! :-)
Thank you for the help!!!
