### ISSUE TITLE
Update to development PlatformIO version

### ISSUE THREAD

**Issue by tabchas** [gepd/Deviot#31]
How can we use the development version of PlatformIO? There is a SAMD uploading issue which has  been fixed as of today, but is only available on the latest dev version of PlatformIO. 

Atom has an option for PlatformIO to update to latest (even non-stable versions), does Deviot have something similar? If not, whats a quick fix that we can do for now?

Here is link to SAMD issue at PlatformIO: platformio/platformio#520 (comment)

**Comment by gepd** [comment]
A fast solution I can bring you is:

- Download [this branch](https://github.com/gepd/Deviot/archive/feature/pio_develop.zip)
- Remove the previous version of deviot; `ST Menu > Preferences > Browse Packages` Remove the `Deviot` folder
- Remove the deviot user preferences folder;  `ST Menu > Preferences > Browse Packages` go to `User` folder and remove `Deviot`
- Restart ST

After that, the`platformio dev` version should start to be installed
I'll improve this feature in the next release.

**Comment by tabchas** [comment]
Sweet! A suggestion is to have a little check mark option in the settings.

For reference, here is how it is currently implemented in the Atom IDE for PlatformIO.

![alt text](http://i.imgur.com/lUKkIHh.png)

**Comment by tabchas** [comment]
@gepd Hmm, are you sure that its pulling from the develop branch of PlatformIO? Where is that specified in the code?

**Comment by gepd** [comment]
I'm sure: https://github.com/gepd/Deviot/blob/feature/pio_develop/libs/Install.py#L188

**Comment by tabchas** [comment]
@gepd Sweet, looks like its working! Thanks for the quick fix. Will be a good addition for a future release 👍 .
