### ISSUE TITLE
Error: Unknown environment names 'due'. Valid names are 'dueUSB'

### ISSUE THREAD

**Issue by guilhermeaugustos** [gepd/Deviot#33]
I can compile and upload for Due using progamming port at first. But when next I modify something and try to reupload this erros apears.

**Comment by gepd** [comment]
Please go to `Deviot Menu > Options > Update Platformio` if you have an old version of platformio it will be updated, if it doesn't solve the problem, please let me here the code are you using to try other solution.

**Comment by guilhermeaugustos** [comment]
Really, my Platformio it was not updated. Apparently everything is working fine, thank you for your help.

**Comment by thomsna** [comment]
I get the same type of error when selecting Arduino Zero (USB Native Port):

Error: Unknown environment names 'zeroUSB'. Valid names are 'mzeroproUSB, teensy31, pro16MHzatmega328, micro, mzeroUSB, uno'

**Comment by thomsna** [comment]
I don't have the error anymore after I deselected "Keep Temp Files" in Deviot Menu > Options

**Comment by ahart2869** [comment]
I get the below error when attempting to compile what am I doing wrong.
Error: Unknown environment names 'STM32F103RC_creality'. Valid names are 'include_tree'
