### ISSUE TITLE
updating cores / packages ?

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#35]
esp8266 core was updated to 2.3.0.
How do i go about updating it in deviot/stino/platformio

Is there any useful cli support for this in either of these platforms ?

**Comment by gepd** [comment]
Yes, you can update platformio from `Deviot menu > Options > Update platformio`
I'll improve this feature in the next release.

**Comment by tablatronix** [comment]
when i run this however 
it does not say anything, just stops.

```
[ Deviot 1.1.9 ]
Checking for PlatformIO updates...
```

**Comment by gepd** [comment]
Please update deviot from the package control (`ctrl+shift+p` > `Package Control: Upgrade Package`) it was a bug, I've fixed in that version (`v1.1.10`)

**Comment by tablatronix** [comment]
working now, package manager was not picking up 1.1.10, must have been cached, I had to restart sublime text.

Thanks.
