### ISSUE TITLE
Not detecting platformio

### ISSUE THREAD

**Issue by sticilface** [gepd/Deviot#4]
doesn't seem to figure it out.  I just get the menu with 1 and 2 and check.  But nothing happens

using mac, with platformio installed.. 

any help appreciated?

**Comment by gepd** [comment]
When you run `platformio --version` in the terminal what is your output?

**Comment by sticilface** [comment]
PlatformIO, version 2.7.0

**Comment by gepd** [comment]
@sticilface I've pushed some changes in the code, I have not tested in the UNIX environment, but it should work. Let me know if that solve your issue.

**Comment by sticilface** [comment]
Sorry that took me a while to get back to you.  
It works.  Good work.  

Next question.  OTA?  

the arudino environment does it via mDNS, but platformio uses specified IP addresses.  Are either of these options available?

**Comment by ivankravets** [comment]
You can use mDNS with @PlatformIO too. See http://docs.platformio.org/en/latest/platforms/espressif.html#over-the-air-ota-update

**Comment by gepd** [comment]
@sticilface It will have for sure! As I'm not have any OTA device in this moment I haven't had not the opportunity to implement this feature. This plugin has a little difference detecting the ports, but I'll try to add it ASAP, I'll let you know when this feature is available.

**Comment by sticilface** [comment]
That is not quite what i meant.  The arduinoIDE has autodiscovery using mDNS, so the IDE can pick up the ESPs on the network, and they appear in the boards/ports list.  

@gepd cheers :)

**Comment by gepd** [comment]
@sticilface The auto discover feature is available now in version `1.2.0`
