### ISSUE TITLE
BUG: UI console resizes every time you upload

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#42]
Do upload
resize console
Do upload

console snaps back to default size

**Comment by tablatronix** [comment]
#44

**Comment by tablatronix** [comment]
changed title since it seems the size is preserved when there is activity, it simply reopens, but if you reupload it resets.

**Comment by gepd** [comment]
I've found a solution for this issue, I'll implement this in the version 1.2 of the plugin

**Comment by gepd** [comment]
I'll close this issue, if you find any problem with this feature, please re-open it
