### ISSUE TITLE
Console closes and cannot be reopened

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#44]
I do not see a way to bring back console.

hitting esc or bringing up sublime console, hides the deviot console.

**Comment by tablatronix** [comment]
Also if you try to use the search bar the console disappears, but it pops back up if there is Activity with the same size. So searching is not possible when the console is busy.

Might have to consolidate all these, as they seem to be sublime limitations perhaps.

**Comment by gepd** [comment]
The same solution I've found for https://github.com/gepd/Deviot/issues/42 will allow to reopen the console. The issue with the search bar sadly there are not much to do because is how ST works

**Comment by gepd** [comment]
Same here: I'll close this issue, if you find any problem with this feature, please re-open it
