### ISSUE TITLE
1.2 console syntax coloring?

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#48]
Is this a feature you added, i notice my console is syntax highlighted, but only if verbose is not enabled.

Is this a feature or is this something my install is doing ?

Also any idea why verbose is not themed ?

Either way it is very nice touch.

**Comment by gepd** [comment]
I still have to work to add colors in verbose mode :P I hope to do it soon

what you mean whith themed?

**Comment by tablatronix** [comment]
I meant colored, glad to hear.

**Comment by gepd** [comment]
This feature has been added too!
