### ISSUE TITLE
feature platformio command line 

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#51]
was just thinking it might be useful to run platform io commands in env from a cmd input entry.
( I do not think st3 has a robust sys console solution, wbond has something though )

**Comment by tablatronix** [comment]
by console I mean like terminal in platformio ide, etc

**Comment by gepd** [comment]
I'll check about this, I've this on my mind for a while, but I haven't had the time to check it. After release v1.2 I'll start to work on that

**Comment by tablatronix** [comment]
https://github.com/chrissimpkins/glue
Thats the one I saw i have not tried it yet.

**Comment by gepd** [comment]
I've been testing this, it seems very interesting I'll start to do some implementations in Deviot, thanks for pointing it!
It will be the first feature to the next mayor release!

**Comment by tablatronix** [comment]
how do you currently run cli commands ?

say i wanted to install another env
`platformio platform install https://github.com/platformio/platform-espressif8266.git#feature/stage`

**Comment by gepd** [comment]
Done.
