### ISSUE TITLE
Menus just disappeared during upgrade ?

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#54]
Did you just push an update version ?
I noticed my Deviot sub menus all disappeared, and I had to restart ST.

Just an FYI for UX.

**Comment by gepd** [comment]
Did you only retart ST? I've released version 1.2.2 a week ago, I'll make some test to avoid that problem in the next update

**Comment by tablatronix** [comment]
I think I started it then noticed it was messed up, kept using it , restarted was still messed up then after a few minutes saw my menus back again. Seems like it always takes a little while to initialize sometimes also if that is related or not sure.

**Comment by gepd** [comment]
I've add a fix for that issue, now it should recover the menu automatically, if it doesn't restart ST will do
