### ISSUE TITLE
Console Error after build. Doesn't affect anything though.

### ISSUE THREAD

**Issue by garvamel** [gepd/Deviot#62]
Hello!

I'm in OSX, with ST3, and Deviot developer branch.

After build, ST console shows the following error:

```
Exception in thread Thread-265:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/PlatformioCLI.py", line 280, in build
    Tools.ERRORS_LIST.extend(Tools.highlightError(exec_view))
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/Tools.py", line 750, in highlightError
    if(string_before in current_line):
UnboundLocalError: local variable 'string_before' referenced before assignment
```

The only thing I can notice, is that if building fails or has warnings for some reason, the issues displayed lack capitalized letters, even if code has them.

Hope it helps!

**Comment by garvamel** [comment]
Update:

Updated PlatformIO and restarted sublime. Caps are back but error persists.

**Comment by gepd** [comment]
Thanks for you report @garvamel I had noted that error some days ago. it's caused because the highlight function. You shouldn't have problem to build or upload your firmware, I'm working to fix and improve that feature in the next release.

**Comment by garvamel** [comment]
The second issue I noticed is that It only randomly enables the function  "click warning/error and go to line". Most of the time it doesn't work.

Thanks!

**Comment by gepd** [comment]
Yes, it's related to the same issue, I'll let you know when all this be fixed

**Comment by gepd** [comment]
Can you try the [develop](https://github.com/gepd/Deviot/tree/develop) branch and check if the go to line error is working now?

**Comment by garvamel** [comment]
Seems to work perfectly!

**Comment by gepd** [comment]
Thanks for your report!
