### ISSUE TITLE
new odd behavior in 1.25+ change serial port triggers upload

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#70]
I noticed recently , when I change a serial port, it automatically starts uploading the current project.
This is very annoying, not sure what is causing it. Or if it always happens, or if its related to #69 issues I am testing.

**Comment by tablatronix** [comment]
It also opens serial monitor as well.
I can see where this would be a feature, I am just not sure how it could work though.

**Comment by gepd** [comment]
Isn't a feature, I'm working to solve all the bugs you reported, I hope to have a solution today

**Comment by gepd** [comment]
This bug should be fixed with https://github.com/gepd/Deviot/commit/d66b36425293da4cdfc4e39d07bc83acbbd4acc9 let me know if you keep getting this behavior

**Comment by airdrummingfool** [comment]
I had this issue on 1.2.5, but it appears to be fixed on the `develop` branch.
