### ISSUE TITLE
default serial port speeds ?

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#71]
How can we modify the default serial monitor drop down speeds ?
I want to add 
74880 ( esp8266 bootloader )
921600, commonly used

**Comment by gepd** [comment]
Open the file `menu_main.json` located in `Packages\Deviot\Preset` and adds the desired speed, after change and save the change go to `Deviot Menu > Language` and select the same language in use. Accept the warning to restart. After restart the new speed will appear.

**Comment by tablatronix** [comment]
works, thanks!

**Comment by tablatronix** [comment]
Has this moved, I do not see serial baud in that file anyhmore.

**Comment by gepd** [comment]
Yes, now it's in: https://github.com/gepd/Deviot/blob/develop/libraries/quick_menu.py#L519

**Comment by gepd** [comment]
I've added `74880` as default

**Comment by tablatronix** [comment]
ahh so its hardcoded again, thanks
