### ISSUE TITLE
Can't select serial port

### ISSUE THREAD

**Issue by monkianer** [gepd/Deviot#72]
Hi I'm using sublime-text 3126 and can't get serial port to setup.
These are error from my console. Is there anything I can do to fix it??
Thanks!
```
Command ""/Users/userName/Library/Application Support/Sublime Text 3/Packages/User/Deviot/penv/bin/python" -u -c "import setuptools, tokenize;__file__='/private/var/folders/02/lrycd0rd20b_zp_tqd5n5mf00000gn/T/pip-build-nxQ0rj/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/02/lrycd0rd20b_zp_tqd5n5mf00000gn/T/pip-gVJbc7-record/install-record.txt --single-version-externally-managed --compile --install-headers "/Users/userName/Library/Application Support/Sublime Text 3/Packages/User/Deviot/penv/include/site/python2.7/netifaces"" failed with error code 1 in /private/var/folders/02/lrycd0rd20b_zp_tqd5n5mf00000gn/T/pip-build-nxQ0rj/netifaces/

Traceback (most recent call last):
  File "/Users/userName/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/mDNS.py", line 3, in <module>
    from zeroconf import ServiceBrowser, Zeroconf
ImportError: No module named zeroconf
```

**Comment by monkianer** [comment]
I got it solved. Since this problem is after updated to macOS Sierra I need to agree to the Xcode/iOS license again.

**Comment by gepd** [comment]
Thanks for the report, I'm currently working to fix some problems related with zeroconf and the option to select a serial port

**Comment by tablatronix** [comment]
Also having this issue.

I also get this, not sure if it has any relation
```
   xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'cc' failed with exit status 1
```

**Comment by tablatronix** [comment]
Any clue what 'agree to the xcode license" has to do with fixing this issue, or how ?

I also saw that the pip folder was being created and cleaned up, so maybe an order problem, not sure why wheel is failing.

what version of netifaces ? 
http://stackoverflow.com/a/28797566/1824214

**Comment by gepd** [comment]
I really don't know what is the problem with xcode and since I don't have any mac machine I can't test it.

The last version of netifaces `0.10.5` has a problem so I'm installing `netifaces 0.10.4` 

You are right that path is wrong, I think it should be `Deviot/penv/Lib/site-packages` where is the call to that path?

**Comment by tablatronix** [comment]
I ran out of time debugging was just trying to log what I was seeing. Ill dig into the source and see what this is trying to do when I have time. I think even master was failing. I gave up and had to do a restore to get back up.

**Comment by tablatronix** [comment]
missing xcode command line tools ughh, must have been the osx upgrade

`xcode-select --install`
fixes for me

**Comment by neophytos-theodorou** [comment]
Had a similar problem on Mint Linux. The workaround is to download the zeroconf.py from [https://github.com/paulsm/pyzeroconf/blob/master/Zeroconf.py](url) and save it in  ~/.config/sublime-text-3/Packages/Deviot/libs.
@gepd please add the specific file in the package distribution.
