### ISSUE TITLE
Where is Deviot's platformio located?

### ISSUE THREAD

**Issue by garvamel** [gepd/Deviot#74]
I need to add a custom board. Thanks!

**Comment by gepd** [comment]
Follow this topic, specially for the json format: https://github.com/gepd/Deviot/issues/58 (last comment)

At this moment I haven't any option go directly to the boards folder, but and easy way is:

`Deviot > Library Options > Open Library Folder` You should back one directory until `.platformio`. Create a new folder `boards` and save your json file there.

To update the board list, look https://github.com/gepd/Deviot/issues/58#issuecomment-244584498

**Comment by garvamel** [comment]
Thanks!

As a follow up question, can I point Deviot to the system-wide installation of Platformio? It seems a little bit more intuitive and useful to me.

**Comment by garvamel** [comment]
Thanks!
