### ISSUE TITLE
PlatformIO projects get re-initialized

### ISSUE THREAD

**Issue by garvamel** [gepd/Deviot#76]
I opened ST by dragging a PlatformIO project folder to sublime launcher (on macOS Sierra, but happened on OSX El Capitan as well). The project uses a different environment than the last build done with Deviot (Deviot seems to remeber the last environment used), so upon build, it initialized the project again, effectively adding the old environment to the project.

Maybe Deviot could check for a `platformio.ini` file first and set the environment automatically?

Thanks!

**Comment by gepd** [comment]
Please read: https://github.com/gepd/Deviot/issues/117
