### ISSUE TITLE
No new line in console output

### ISSUE THREAD

**Issue by AKBON** [gepd/Deviot#8]
Hi,

I have the problem, that in the console output everything goes into an endless string instead of beginning a new line for every statement. In your animated gifs everything looks fine. Is that a matter of preferences or what could be the reason?

Thx!

**Comment by gepd** [comment]
what development board are you using?

**Comment by AKBON** [comment]
Hi, it's not code depended. I mean the outputs of deviot in the console, while compiling or setting up something. That all goes into a long string with no line break in the sublime window. Console was the wrong word, I am not sure how it's called correctly^^

**Comment by gepd** [comment]
You can said console, I'll understand,
To know where is the problem, I need to replicate the conditions of your project, without that information there is not much I can help. As you noted in the gift, with my setup all works fine.

**Comment by AKBON** [comment]
It already hapens directly after installation of the plugin, so not much configuration has been done. My first try was uploading an example sketch to a NodeMCU ESP 8266. The problem is reproducable on other windows machines.

**Comment by gepd** [comment]
can you provide me the link to the example sketch?

**Comment by AKBON** [comment]
It occurs everytime, no matter what code is used and I'm not sure how the code could influence the console output. Consider the standard Arduino blink example, than the console output after building looks like this:

[ Deviot 1.1.3 ] Blink.ino
init_project_11:21:02success_took_5.96built_project_11:21:08

Another Issue: The names of the menu items are also not correct, they are like "menu_new_sketch" and so on.

Interesting: Problem seems only to exist on Windows, on a MAC the output and the menu items are both fine.

Could it be a problem with a parallel installation of Stino?

**Comment by gepd** [comment]
Now I understand the issue, always adds the most information possible to understand the problem.

I've deviot installed in multiple O.S and I haven't that error, try disabling stino from the package control options and restarting ST.

you said It happens to you in all versions of windows or you tried a specific one?

**Comment by AKBON** [comment]
Hi, it happens in XP an Win 7, that's where I could test it. I just made a fresh installation on my private laptop (Win 7) which never had contact to Stino and the problems are the same. Incorrect menu item names and no line break. Switching the language did not help.

**Comment by gepd** [comment]
What is the default language in your machines? I'm thinking it can be because you're using a different language. (I'm just guessing)

Most problems with icons is because ST has problem with different OS, and don't support graphic buttons, I'm looking for a better solution.

**Comment by AKBON** [comment]
System default language is German.

**Comment by gepd** [comment]
Thanks, I know what can be the problem, it will be solved in the next release.
