### ISSUE TITLE
Progress Thread hangs on compile failure

### ISSUE THREAD

**Issue by ubidefeo** [gepd/Deviot#81]
hi there

I have been noticing this behaviour lately.
When a compile task fails, the bottom of the window keeps displaying a progress bar in which the `=` indicator keeps jumping to random positions.
I think the Progress Thread gets stuck and doesn't timeout or something.
if I recompile and it fails again and again then Sublime Text hangs and I have to force-quit it.

I'm on the **develop** branch
here's a screenshot of a failed compilation
<img width="621" alt="screen shot 2016-10-24 at 16 52 52" src="https://cloud.githubusercontent.com/assets/1894487/19650889/1aa2eaca-9a0b-11e6-935d-2c3687705548.png">

**Comment by gepd** [comment]
Thanks for your report @ubidefeo I've noticed this behavior too. The plugin has a lot of this kind of bugs, that is why I started to write the plugin from scratch, I still don't have all the basic functions to release a  alpha, but I hope to do it soon.

**Comment by gepd** [comment]
Please read https://github.com/gepd/Deviot/issues/117
