### ISSUE TITLE
feature Serial send history

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#84]
Would it be possible to add up arrow history recall in the serial send input line ?

**Comment by gepd** [comment]
Add an arrow I think is not possible, but I'm thinking in a option to how the history in the same window as the boards are shown in this moment... I'll let you know when this option be available to test

**Comment by tablatronix** [comment]
I mean like press "up arrow" like in shells to go back in history

**Comment by gepd** [comment]
I'll let this to the next release

**Comment by gepd** [comment]
Done, it will be available in the next release, but you can try it from the develop branch
