### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by merlinplaygames** [gepd/Deviot#90]
I don't have highlighted words: boolean, byte, word.
And for example constants like INPUT,OUTPUT, and they are not highlighted in functions like seput() or loop().
![motor arduino](https://cloud.githubusercontent.com/assets/11756007/20652275/ab795e02-b4f6-11e6-9691-e46b4581713f.png)

Im using ST3 3126

**Comment by gepd** [comment]
I'll try to check the syntax highlight soon, I'm preparing a new version of the plugin but this days I'm not with much time, may be I'll push a change to this branch first.

**Comment by gepd** [comment]
Done in Deviot 2.0
