### ISSUE TITLE
Show size of program after build, upload

### ISSUE THREAD

**Issue by dpeters19** [gepd/Deviot#91]
The standalone Arduino IDE and [Stino](https://github.com/Robot-Will/Stino) both print out the size of the program after builds and compiles. Maybe we can have this feature too?

**Comment by gepd** [comment]
To have all that information you can activate the full output from `Deviot Menu > Options > Full Verbose Output When Build`

**Comment by LordFlashmeow** [comment]
I just feel like it should be enabled by default; there's a lot of extra stuff I don't need to see with verbose output.
